### ISSUE TITLE
Modify my SVG color

### ISSUE THREAD

**Issue by Hexagoo** [GerritErpenstein/ionic2-custom-icons#25]
Hey, I want to create a page where people can select their music styles.

I made a mockup:
![example_poi](https://user-images.githubusercontent.com/14003264/29003359-a2e6fa26-7ab5-11e7-8efc-af7726c224cf.png)

The problem with this SVG is they have a white cercle with a low opacity.
After activated it, the logo takes a blue color and the cercle is totally white.

Can I make this with 'ionic2-custom-icons'?
How can I say to the script that I want this part of the SVG has this color and the other part has an other color? :)

**Comment by GerritErpenstein** [comment]
Hi @Hexagoo,
that should be possible solely with CSS. Try something like this:

```html
<custom-icon set="my-set" name="icon-a" class="overview"></custom-icon>
<custom-icon set="my-set" name="icon-b" class="overview active"></custom-icon>
```

```css
custom-icon.overview {
   font-size: 150px;
   color: #ffffff;
   background-color:rgba(255, 255, 255, 0.5);
   border-radius: 50%;
   width: 150px;
   height: 150px;
}

custom-icon.overview.active {
   color: #4fb3d4;
   background-color:rgba(255, 255, 255, 1);
}

```
